apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: testdata-reset
  namespace: flex
  labels:
    team: flex
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: flex
      application: flex-testdata-reset
      access: write
    - team: flex
      application: syfosyketilfelle
      access: read
    - team: flex
      application: flex-syketilfelle
      access: read
    - team: flex
      application: spinnsyn-backend
      access: read
    - team: flex
      application: flex-juridisk-vurdering-test-backend
      access: read
    - team: flex
      application: sykepengesoknad-backend
      access: read
    - team: flex
      application: ditt-sykefravaer-backend
      access: read
    - team: flex
      application: flex-testdata-generator
      access: write
