apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: test-command
  namespace: flex
  labels:
    team: flex
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: flex
      application: sykepengesoknad-backend
      access: read
    - team: flex
      application: flex-testdata-generator
      access: write
