apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-testdata-generator
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://flex-testdata-generator.dev.nav.no"
    - "https://flex-vedtak-mock.dev.nav.no"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
    path: api/isAlive
  readiness:
    path: api/isReady
  kafka:
    pool: nav-dev
  env:
    - name: MOCK_BACKEND
      value: "false"
