apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-testdata-generator
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - {{ingress}}
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 300Mi
  liveness:
    path: api/isAlive
  readiness:
    path: api/isReady
  startup:
    path: api/isAlive
    initialDelay: 10
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: dokarkiv.dev-fss-pub.nais.io
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: DOKARKIV_CLIENT_ID
      value: "api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default"
